//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Projekt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DogsBaseEntities : DbContext
    {
        public DogsBaseEntities()
            : base("name=DogsBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dogs> Dogs { get; set; }
        public virtual DbSet<DogsOwner> DogsOwner { get; set; }
        public virtual DbSet<Jurors> Jurors { get; set; }
        public virtual DbSet<Scores> Scores { get; set; }
    }
}
