//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int Score_id { get; set; }
        public int Outfit { get; set; }
        public int Speed { get; set; }
        public int Focus { get; set; }
        public int Total { get; set; }
        public int Dog_id { get; set; }
        public int Juror_id { get; set; }
    
        public virtual Dog Dog { get; set; }
        public virtual Juror Juror { get; set; }
    }
}
